### ISSUE TITLE
Chore: Create `GitHub` Personal Access Token for `CI` / `Dependabot`

### ISSUE THREAD

**Issue by nelsonic** [dwyl/who#208]
at present our PR: #207 fails `CI` because it doesn't have a token to access the `API`. 💔 

# TODO:

+ [x] Create Access Token without expiry. 
+ [x] store it super securely in vault
+ [x] Add to CI 
+ [x] Confirm working 👌

**Comment by nelsonic** [comment]
Doing this _now_ as it's a quick-win. 🧑‍💻 ⏳ 5️⃣

**Comment by nelsonic** [comment]
Added to: https://github.com/dwyl/who/settings/secrets/actions

**Comment by nelsonic** [comment]
Working: https://github.com/dwyl/who/actions/runs/12321509388/job/34393071780
<img width="1305" alt="image" src="https://github.com/user-attachments/assets/74540fee-6d64-4766-be6f-aa9c410dcef3" />


And apparently there's a new `chrome` available ... 🙃
