### ISSUE TITLE
Feat: Create (`GitHub`) `profile` schema to store `public` profile data

### ISSUE THREAD

**Issue by nelsonic** [dwyl/who#85]
In order to enable all other features of this mini-app, we need to comprehensively capture profile data.

# Todo

+ [x] Map all the fields from the `GitHub` "User" object into a `profile` schema in _this_ repo. 
  + [x] Use `String` for all values except:
    + [x]  `"public_repos": 2, "public_gists": 1, "followers": 20,  "following": 0, "id": 1` appear to be `Int` and 
    + [x] `"hireable": false, "site_admin": false` look like `boolean`
    + [x] use appropriate date/time for  `"created_at": "2008-01-14T04:33:35Z", "updated_at": "2008-01-14T04:33:35Z"` so that we can query this data. 
  + [x] Create sample data to test `CRUD`.

https://docs.github.com/en/rest/users/users?apiVersion=2022-11-28#get-a-user

```json
{
  "login": "octocat",
  "id": 1,
  "node_id": "MDQ6VXNlcjE=",
  "avatar_url": "https://github.com/images/error/octocat_happy.gif",
  "gravatar_id": "",
  "url": "https://api.github.com/users/octocat",
  "html_url": "https://github.com/octocat",
  "followers_url": "https://api.github.com/users/octocat/followers",
  "following_url": "https://api.github.com/users/octocat/following{/other_user}",
  "gists_url": "https://api.github.com/users/octocat/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/octocat/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/octocat/subscriptions",
  "organizations_url": "https://api.github.com/users/octocat/orgs",
  "repos_url": "https://api.github.com/users/octocat/repos",
  "events_url": "https://api.github.com/users/octocat/events{/privacy}",
  "received_events_url": "https://api.github.com/users/octocat/received_events",
  "type": "User",
  "site_admin": false,
  "name": "monalisa octocat",
  "company": "GitHub",
  "blog": "https://github.com/blog",
  "location": "San Francisco",
  "email": "octocat@github.com",
  "hireable": false,
  "bio": "There once was...",
  "twitter_username": "monatheoctocat",
  "public_repos": 2,
  "public_gists": 1,
  "followers": 20,
  "following": 0,
  "created_at": "2008-01-14T04:33:35Z",
  "updated_at": "2008-01-14T04:33:35Z"
}
```

+ [x] Create PR adding this schema to the app. 🙏  -> https://github.com/dwyl/who/pull/207

**Comment by nelsonic** [comment]
@SimonLab as discussed on our call, if you have some time to do this it would be very helpful. 
Ultimately our goal with tracking the `people` who are starring/watching/contributing to our projects is:
1. Giving people credit for contributing by putting their names & avatar on the @dwyl website 👤 
2. Showing how many _distinct_ people have starred our repos (vanity metric but good social proof)
3. Showing how many people from well-known ***`companies`*** are using our code, again very good social proof.

The reason this 3rd one is relevant to you in your current "Job Search" is that you can put it on your profile https://github.com/SimonLab/SimonLab/issues/1 to add some "proof" (help you stand out from the crowd) in a job application. 

If you can write: "Code I've written is used by _many_ companies you have heard of" 
and provide a list with 100+ well-recognised logos, it's a _lot_ more interesting to the recruiter/hiring manager 
than just writing "I've written some code for a few projects ..." 
It's more concrete and relatable. 
You'll soon see from doing this that @dwyl code is used by _most_ of the Fortune 500. 
That sets you apart from 99% of devs.

**Comment by nelsonic** [comment]
Not quite what I wanted ... 💭 
I just want a way of sending data to the Client as it comes in ...

**Comment by nelsonic** [comment]
Reading: https://dev.to/azyzz/network-optimization-for-sending-lot-of-data-from-liveview-to-client-using-pushevent-2nl

**Comment by nelsonic** [comment]
Figured out what was not working!!
Was using `Endpoint.broadcast_from/4` instead of `Endpoint.broadcast/3`
which only sends the updates to the _other_ clients, not the one that is in-focus.
i.e. having multiple browsers open helped me understand this _was_ working just not in the browser I was focussed on!

**Comment by nelsonic** [comment]
Have this working on my branch: https://github.com/dwyl/who/pull/207 :shipit: 
It _seems_ simple (and it is, really!) but I want to _stream_ the API responses to the client as they come in. ⏳ 
_Definitely_ over-complicating it, but the _experience_ will be good. 👌

**Comment by nelsonic** [comment]
`user` data including everything we want to display (for now) is being ingested on `localhost`:
<img width="2227" alt="Image" src="https://github.com/user-attachments/assets/5b343365-a5fc-4aa0-8410-e9e3e1d246d2" />

All code included in #207 🚢 
Closing. ✅
